# -*- coding: utf-8 -*-
"""document_checker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NvnZuQJYt4q7JoglBxEJk6frpPVXUnvR
"""

from doctr.io import DocumentFile
from doctr.models import ocr_predictor
model = ocr_predictor(det_arch = 'db_resnet50', reco_arch = 'crnn_vgg16_bn', pretrained = True)

img_path = "hehe.jpg" #Specify your image path here
img = DocumentFile.from_images(img_path)
result = model(img)
output = result.export()

import json
with open("docTR_OCR_output.json", "w") as f:
    f.write(json.dumps(output, indent=1))
f.close()

result.show(img)

# Define the function to search for a target string
def find_and_prompt(ocr_output, target_string):
    full_text = " ".join([obj3["value"] for obj1 in ocr_output['pages'][0]["blocks"] for obj2 in obj1["lines"] for obj3 in obj2["words"]])

    if target_string.lower() in full_text.lower():
        print(f"The string '{target_string}' was found in the document.")
        return True
    else:
        print(f"The string '{target_string}' was not found in the document.")
        return False

# Save the OCR output to a JSON file
with open("docTR_OCR_output.json", "w") as f:
    json.dump(output, f, indent=1)

# Example usage of the find_and_prompt function
find_and_prompt(output, "Sahil Khan")

